### ISSUE TITLE
Conda env build being killed

### ISSUE THREAD

**Issue by YasCoMa** [cicese-biocom/esm-AxP-GDL#13]
In a laptop with 16gb of memory, the instruction to create the environment get the computer stuck or the terminal is killed. In the readme there is no severe requirement of ram memory, but apparently it needs more than 16gb.

**Comment by grenetercd** [comment]
Thank you very much for your comment, I will perform the necessary validations to determine the minimum hardware requirements and detail it in the README.md file. Particularly, on an AMD Ryzen laptop with 16GB of RAM, I successfully installed the framework using Docker. On a PC with 32GB of RAM I have installed and used the framework successfully. This framework is only compatible with Linux operating systems, CUDA Toolkit version 11 (tested with version 11.3), C++ Compiler version 9.2, and Python version 3.7 to 3.9. 

To install the framework dependencies on a local environment, it is recommended:
1. Install the tools: CUDA Toolkit 11.3, C++ Compiler 9.2, and Anaconda or Miniconda.
2. Create the Conda environment on the command line (terminal) with the following command: conda env create -f environment.yml. 
3. Activate the Conda environment on the command line (terminal) with the following command: conda env create -f environment.yml. 
4. Verify that the Conda environment was successfully activated in the command line (terminal) with the following command: conda env list.

To install the framework dependencies in a Docker environment it is recommended:
1. To install Docker following the installation guide available at: https://docs.docker.com/engine/installation/.
2. To Install CUDA Toolkit 11.3. 
3. To build the Docker image locally using the following command line: docker-compose build. Firstly, it is to change to the directory containing the docker-compose.yml file.

**Comment by YasCoMa** [comment]
I was only able to build the env inside a GPU node in a cluster, with 25GB of ram. But now it is giving me this error:
 CRITICAL [tertiary_structure_handler.py:40] Sequences not linked to PDB or with error when analyzing the PDB structure.
 I pointed the pdb structures folder to a pdbmirror folder, in the structures subfolder (with .ent files in it).

**Comment by YasCoMa** [comment]
I just saw here that it expects a pdb representation of the input entries, we have to predict the epitopes structures before using the tool.

**Comment by grenetercd** [comment]
The current version of the framework only supports PDB files as input. In your case, the 3D structures of the epitopes must be provided in PDB format, or they can be predicted in the framework using the ESMFold model. 

The framework receives a comma separated value (CSV) file as input, which contains the sequence IDs, the amino acid sequences, as well as the activity (0 and 1 for negative and positive activities, respectively) and the partition (training, validation and test) of each sequence. This CSV file must be always given as input. In your case, the .ent files must be converted to pdb file, and the name of the pdb files must coincide with the sequence IDs in the input CSV file. Otherwise, an error similar to the one obtained by you will be thrown.

Notice that if you want to use our models to predict your data, the input CSV file will only contain the sequence IDs and the amino acid sequences.

**Comment by YasCoMa** [comment]
Hello, I tried to pass only the id and sequence (because i only want to predict), and it is returning error because it is not finding the activity column. Actually, the data validator needs all the four columns, it does not matter if it is train, test or inference.

Also, in line 172 of graph.edge_construction_functions, it should be a try and except to not stop the whole pipeline because it is breaking the matrix filling process or this if statement:
if( j < number_of_amino_acid ):

Again, in line 411 of workflow.gdl_workflow, you should initialize auc with 0, because at the end when formatting to string it only accept number not None.

In inference.sh (the one i am using), it is not expecting the dropout_rate argument, i had to remove it to start the process.

**Comment by grenetercd** [comment]
We are very grateful for your comments. We have detected a few bugs, which have been corrected and here are the details:

We detected a minor bug in the inference.sh file, where the test.py function was being invoked instead of the inference.py function to run inference mode. So, you need only to specify the sequence IDs and amino acid sequences of your dataset as I previously commented to you .
 
The dropout_rate parameter has been removed from the inference.sh file. The dropout rate to run the inference mode is incluided in the .pt files corresponding to the models. In this way, the same dropout rate used during the training of the models is the same one to be used during the inference stage.

The bug related to the None type during the AUC calculation was also resolved.

We recommend re-downloading the framework and the corresponding .pt files for each model. In addition, we have provided in the example folder two datasets:

- ExampleDataset.csv can be used to assess the training, testing and inference modes in the framework.
- ExampleDatasetInference.csv is specifically designed to assess the inference mode.

**Comment by grenetercd** [comment]
Hello, I wanted to ask you if you were able to successfully run the framework. If there are any problems or if you need help, feel free to contact me and I will be happy to help you.

**Comment by YasCoMa** [comment]
Thanks for the feedback. I was only able to run for few proteins in one of the models because of the memory requirements. But it is working, i just do not have computational resources to run the analysis for my entire data. I tested with some proteins of my data, because i could use blastp against pdb to retrieve the closest to obtain the structure pdb. Also, i have a lot of peptide sequences of epitopes, but i am not able to run one by one in web services like per-fold to predict the pdb structure for all of them, to use as input for the tool.
